### ISSUE TITLE
Hi Torsen

### ISSUE THREAD

**Issue by EricFournier3** [tseemann/legsta#11]
Hi Torsen, i am wondering if the script works fine with concatenation of the 7 sequences in one fasta file instead of a whole genome sequence. We have only data from first generation sequencing. Actually, i tried it and it doesn't works.

Thanks
Eric

**Comment by tseemann** [comment]
@EricFournier3 it probably will not work because it relies in _in silico_ PCR so if you don't have the primers in the template you sequenced it won't be able to find the amplicons?  The primers are essential to distinguising the `mompS` paralog.

However, you could make an `mlst` database from the SBT files and use `mlst` because that uses the sequence alone.
